### ISSUE TITLE
Only first link on each page gets downloaded

### ISSUE THREAD

**Issue by yakzie** [samhagin/linuxacademy-dl#1]
How can I download all videos? Here is what I tried. Only first video get downloaded.

>  [yakzie@control]$ youtube-dl https://linuxacademy.com/cp/modules/view/id/154
> [generic] 154: Requesting header
> [redirect] Following redirect to https://linuxacademy.com/amazon-web-services/training/course/name/aws-certified-cloud-practitioner
> [generic] aws-certified-cloud-practitioner: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] aws-certified-cloud-practitioner: Downloading webpage
> [generic] aws-certified-cloud-practitioner: Extracting information
> [generic] aws-certified-cloud-practitioner: Downloading m3u8 information
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 14
> [download] Destination: AWS Certified Cloud Practitioner-aws-certified-cloud-practitioner.mp4
> [download] 100% of 27.78MiB in 00:10
> [ffmpeg] Fixing malformed AAC bitstream in "AWS Certified Cloud Practitioner-aws-certified-cloud-practitioner.mp4"
> [yakzie@control]$

**Comment by samhagin** [comment]
Are you using youtube-dl or the script within this repo? You should be using the script within this repo.Copy it to a file and run it as below. Using the script works for me and downloads all videos 

```
python linuxacademy-dl.py  username password https://linuxacademy.com/cp/modules/view/id/154
```

output

```
WARNING: Forcing on generic information extractor.
[generic] 154: Downloading webpage
[generic] 154: Extracting information
[generic] 154: Downloading m3u8 information
[download] Sleeping 30 seconds...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 14
[download] Destination: 00001-Linux_Academy.mp4
[download] 100% of 27.78MiB in 00:07
[ffmpeg] Fixing malformed AAC bitstream in "00001-Linux_Academy.mp4"
[generic] 154: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 154: Downloading webpage
[generic] 154: Extracting information
[generic] 154: Downloading m3u8 information
[download] Sleeping 30 seconds...
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 20
[download] Destination: 00002-Linux_Academy.mp4
[download] 100% of 32.59MiB in 00:07
[ffmpeg] Fixing malformed AAC bitstream in "00002-Linux_Academy.mp4"
[generic] 154: Requesting header
WARNING: Forcing on generic information extractor.
[generic] 154: Downloading webpage
[generic] 154: Extracting information
[generic] 154: Downloading m3u8 information
[download] Sleeping 30 seconds...
```

**Comment by yakzie** [comment]
I actually first tried it with youtube-dl. Then I did it how it was supposed to.

> [yakzie@control ~]$ python linuxacademy-dl.py user password https://linuxacademy.com/cp/modules/view/id/154 
> Traceback (most recent call last):
>   File "linuxacademy-dl.py", line 7, in <module>
>     from selenium import webdriver
> ModuleNotFoundError: No module named 'selenium'

Installing selenium

> [yakzie@omega ~]$ sudo pip install selenium
> sudo pip install selenium
> Collecting selenium
>   Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
> Requirement already satisfied: urllib3 in /usr/lib/python3.7/site-packages (from selenium) (1.24.1)
> Installing collected packages: selenium
> Successfully installed selenium-3.141.0
> You are using pip version 19.0.1, however version 19.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

Trying it again

> [yakzie@control ~]$ python linuxacademy-dl.py user password https://linuxacademy.com/cp/modules/view/id/154 
> Traceback (most recent call last):
>   File "linuxacademy-dl.py", line 42, in <module>
>     link.click()
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
>     return self._parent.execute(command, params)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a href="/cp/login" class="btn btn-la-outline">...</a> is not clickable at point (784, 871). Other element would receive the click: <path fill="#ffffff" d="M28,3.2C28,1.5,26.5,0,24.8,0H3.2C1.5,0,0,1.5,0,3.2v11.5C0,16.5,1.5,18,3.2,18h21.5c1.8,0,3.2-1.5,3.2-3.2 V3.2z M24.7,14.8c-0.2,0.1-0.4,0.2-0.6,0.2c-0.2,0-0.4-0.1-0.6-0.3l-5-5.3l-3.6,3c-0.3,0.2-0.6,0.3-0.9,0.3s-0.7-0.1-0.9-0.4l-3.6-3 l-5,5.3c-0.2,0.2-0.4,0.3-0.6,0.3c-0.2,0-0.4-0.1-0.6-0.2c-0.3-0.3-0.4-0.8,0-1.2l4.9-5.3L3.3,4.5C3,4.2,2.9,3.6,3.2,3.3 C3.5,2.9,4,2.9,4.4,3.2l9.6,7.9l9.6-7.9c0.4-0.3,0.9-0.2,1.2,0.1c0.3,0.4,0.2,0.9-0.1,1.2l-4.8,3.9l4.9,5.3 C25.1,14,25,14.5,24.7,14.8z" data-reactid=".0.4.0.2"></path>
>   (Session info: chrome=72.0.3626.81)
>   (Driver info: chromedriver=72.0.3626.81,platform=Linux 4.19.20-1-MANJARO x86_64)

**Comment by yakzie** [comment]
Okay I think I solved it. The problem was that it wasn't opening chromium in full screen. I changed it to full screen and it seems to be working.

**Comment by samhagin** [comment]
I modified the script and it now runs headless ( without opening an actual Chrome window )
