### ISSUE TITLE
Unsupported URL After Successful Login

### ISSUE THREAD

**Issue by CameronJRAllan** [samhagin/linuxacademy-dl#11]
I'm getting an Unsupported URL error when passing the extracted information to YouTube-DL

```
Welcome, I'm excited to have you here

DevTools listening on ws://127.0.0.1:53443/devtools/browser/19555609-d7d1-4f9c-9d60-f625bfd0a101
[0420/103814.900:INFO:CONSOLE(25)] "[Facebook Pixel] - Multiple pixels with conflicting versions were detected on this page.", source: https://connect.facebook.net/en_US/fbevents.js (25)
[0420/103951.742:INFO:CONSOLE(9)] "There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "https://login.linuxacademy.com" to the "Allowed Web Origins" list in the Auth0 dashboard: https://manage.auth0.com/#/clients/KaWxNn1C2Gc7n83W9OFeXltd8Utb5vvx/settings", source: https://cdn.auth0.com/js/lock/11.3/lock.min.js (9)
Getting cookies from login.linuxacademy.com
Sleeping for 5 seconds..
Attempting to login..
[0420/104001.941:INFO:CONSOLE(25)] "[Facebook Pixel] - Duplicate Pixel ID: 1541523966111627.", source: https://connect.facebook.net/en_US/fbevents.js (25)
[0420/104011.752:INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://svc-scheduler.linuxacademy.com/api/v1/schedules/dashboard' from origin 'https://app.linuxacademy.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://app.linuxacademy.com/dashboard (0)
Login successful..
Getting cookies from .linuxacademy.com
Getting lesson links..
[0420/104033.026:INFO:CONSOLE(7)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: https://linuxacademy.com/lib/cache/a78266d49a2bf4774430493de18de174_fbdbce214fecf4bddd3a47e1da75d14f_7b81d4db785ccb9b57c3194091289a74_08e78c06afd7ea977061e81d9d654867_a044903ac3d8345d1923e05e73e45e9c_.js?ver=1555539065 (7)
[0420/104037.790:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20190417/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
ignoring URL
ignoring URL
ignoring URL
ignoring URL
['https://linuxacademy.com/cp/courses/lesson/course/1917/lesson/1/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1917/lesson/2/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1917/lesson/3/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1917/lesson/4/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1938/lesson/1/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1938/lesson/2/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/1/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/2/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/3/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/4/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/5/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/6/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/7/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1937/lesson/8/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/1/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/2/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/3/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/4/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/5/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1939/lesson/6/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1940/lesson/1/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1940/lesson/2/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1940/lesson/3/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1940/lesson/4/module/192', 'https://linuxacademy.com/cp/courses/lesson/course/1941/lesson/1/module/192']
Converting cookie using curl..
Starting download..
[generic] 192: Requesting header
[redirect] Following redirect to https://linuxacademy.com/devops/training/lesson/course/devops-essentials-2018/name/about-the-course-author
[generic] about-the-course-author: Requesting header
WARNING: Forcing on generic information extractor.
[generic] about-the-course-author: Downloading webpage
[generic] about-the-course-author: Extracting information
ERROR: Unsupported URL: https://linuxacademy.com/devops/training/lesson/course/devops-essentials-2018/name/about-the-course-author
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\extractor\common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\extractor\generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://linuxacademy.com/devops/training/lesson/course/devops-essentials-2018/name/about-the-course-author

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 114, in <module>
    ydl.download( urls  )
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 868, in process_ie_result
    extra_info=extra_info)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://linuxacademy.com/devops/training/lesson/course/devops-essentials-2018/name/about-the-course-author
```

Youtube-dl information:
```
C:\Users\XXXX\linuxacademy-dl>youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

```

Chrome version 73, with matching ChromeDriver in correct directory.
Python version 3.6.4

Example URL failing:
`https://linuxacademy.com/cp/modules/view/id/192`

**Comment by CameronJRAllan** [comment]
Running via YouTube and providing a cookies file using the _cookies.txt_ Chrome plugin, I am able to successfully download videos - is this a cookies issue within the script?

**Comment by wywywywy** [comment]
I have the same problem as you.

Currently I am this wee script in the devtools console to get the links from a course page and together with the cookies.txt Chrome extension to download.

`let links = []; document.querySelectorAll('a').forEach((n) => { let link = n.getAttribute('href'); let found = link ? link.includes('/courses/') : false; if (found) links.push('https://linuxacademy.com' + link); }); console.log(links.join('\n'));`

**Comment by RahulShaw** [comment]
I have managed to fix the issue. I'll upload the script soon.

**Comment by ogubchenko** [comment]
@wywywywy i've try yoyr method and still getting unsupported url.
@RahulShaw when the fix will be released?

Thanks.

**Comment by RahulShaw** [comment]
@ogubchenko I'm working on it. Should be done by this weekend at the most.

**Comment by talk2aanand** [comment]
Did you get any solution ?

**Comment by RahulShaw** [comment]
Well, the fix is not fully automated and requires a one-time manual task once in a couple of days. Shall I go ahead and post it?

**Comment by talk2aanand** [comment]
Sure upload it

**Comment by RahulShaw** [comment]
@talk2aanand I'll post it today!

**Comment by RahulShaw** [comment]
Here it is - https://github.com/RahulShaw/LinuxAcademy-DL
