### ISSUE TITLE
Unable to download videos from linuxacademy

### ISSUE THREAD

**Issue by satrox28** [samhagin/linuxacademy-dl#15]
root@ubuntu:~/linuxacademy-dl# python3.7 download.py emailid password https://linuxacademy.com/cp/modules/view/id/245
Welcome, I'm excited to have you here
Traceback (most recent call last):
  File "download.py", line 52, in <module>
    driver = webdriver.Chrome( options=options )
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by karlochacon** [comment]
working for me after following this

https://github.com/samhagin/linuxacademy-dl/issues/19
