### ISSUE TITLE
Unsupported URL while trying to download

### ISSUE THREAD

**Issue by hila3000** [samhagin/linuxacademy-dl#16]
On MacOS Mojave, version 10.14.5
chrome 75 (also chromedriver 75)
I get this error when trying to download a course that I have access to:

Starting download..
[generic] 314: Requesting header
[redirect] Following redirect to https://linuxacademy.com/containers/training/lesson/course/docker-deep-dive-part-1/name/about-this-course
[generic] about-this-course: Requesting header
WARNING: Forcing on generic information extractor.
[generic] about-this-course: Downloading webpage
[generic] about-this-course: Extracting information
ERROR: Unsupported URL: https://linuxacademy.com/containers/training/lesson/course/docker-deep-dive-part-1/name/about-this-course
Traceback (most recent call last):
  File "download.py", line 114, in <module>
    ydl.download( urls  )
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 868, in process_ie_result
    extra_info=extra_info)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://linuxacademy.com/containers/training/lesson/course/docker-deep-dive-part-1/name/about-this-course

I tried following instructions in here:
https://github.com/RahulShaw/LinuxAcademy-DL
but it didn't help :/

What can be done?

**Comment by kh411d** [comment]
yup this is new, happened to me also, my first thought is might be cookie problem, second thought might be the user agent, I already upgrade the youtube-dl but still no luck

**Comment by karlochacon** [comment]
working for me after following this

https://github.com/samhagin/linuxacademy-dl/issues/19
