### ISSUE TITLE
Authentication refused

### ISSUE THREAD

**Issue by GMags** [samhagin/linuxacademy-dl#5]
Hi seems script is having issues authenticating with linux academy

$ python download.py https://linuxacademy.com/cp/modules/view/id/311 -u username -p password
Welcome, I'm exited to have you here
Getting cookies from login.linuxacademy.com
Sleeping for 5 seconds..
Attempting to login..
Login failed..exiting

**Comment by karlochacon** [comment]
this is the way you don't need -u and -p

**Comment by GMags** [comment]
sorry yes that gets me by the authentication step, now i seem to get SSL related issues from youtube-dl

`Traceback (most recent call last):
  File "download.py", line 114, in <module>
    ydl.download( urls  )
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2006, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 817, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 622, in report_error
    self.trouble(error_message, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 592, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))`
