### ISSUE TITLE
Error WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by anutator** [samhagin/linuxacademy-dl#9]
Have errors. Try to download (for example 284 or 281) 
```
Traceback (most recent call last):
  File "download.py", line 46, in <module>
    driver = webdriver.Chrome( options=options )
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 3.10.0-957.5.1.el7.x86_64 x86_64)
```

**Comment by behradeslamifar** [comment]
Script dont have permissions to create cookies.txt. create by yourself with correct permisions.
$ touch cookies.txt

**Comment by masdani78** [comment]
Welcome, I'm excited to have you here
Traceback (most recent call last):
  File "download.py", line 46, in <module>
    driver = webdriver.Chrome( options=options )
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 3.16.0-6-amd64 x86_64)


same problem with anutator.

cookies create.

**Comment by anutator** [comment]
I created cookies.txt with root permissions but it is not a solution as you have to execute sript with user permissions. You must give permissions to parent folder for the user.  It helped me.

**Comment by masdani78** [comment]
if run with user, different error

$ python download.py user@domain.com password https://linuxacademy.com/cp/modules/view/id/327
Welcome, I'm excited to have you here
Traceback (most recent call last):
  File "download.py", line 46, in <module>
    driver = webdriver.Chrome( options=options )
TypeError: __init__() got an unexpected keyword argument 'options'
$ 

any info?
